import type { ConfiguredStorageDriver } from "../../../contracts/Storage";
import type { MemoryStorageConfig } from "./MemoryStorageConfig";
import { MemoryStorageEndpoint } from "./MemoryStorageEndpoint";

/**
 * Create memory-backed storage. This can be used in production as a
 * high-performance disk to store small amounts of temporary data in, and is
 * also useful in tests.
 *
 * The URLs generated by methods like getPublicDownloadUrl() are fake.
 */
export function memoryStorage(config: MemoryStorageConfig = {}): ConfiguredStorageDriver {
	return {
		getEndpoint(container) {
			return container.construct(MemoryStorageEndpoint, config);
		},
	};
}
