import type { StorageAdapter } from "../../../contracts/Storage";
import { MemoryEndpoint } from "./MemoryEndpoint";
import type { MemoryStorageConfig } from "./MemoryStorageConfig";

/**
 * Create memory-backed storage. This can be used in production as a
 * high-performance disk to store small amounts of temporary data in, and is
 * also useful in tests.
 *
 * The URLs generated by methods like getPublicDownloadUrl() are fake.
 */
export function memoryStorage(config: MemoryStorageConfig = {}): StorageAdapter {
	return {
		build(container) {
			return container.construct(MemoryEndpoint, config);
		},
	};
}
